=== paulwedeck/settlers-remake/jsettlers.common/src/main/resources/jsettlers/common/buildings/building.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!--
Create new Building (Author: MarviMarv, 13.01.2021)
	1.	Add Building name to enum “EBuildingType” (uppercase name)
	2.	Add Building to related category in enum “EBuildingsCategory”
	3.	Add Building to enum “EOriginalMapBuildingType” (seems to be deprecated though)
	4.	Add CASE for method “createBuilding” in class “Building” depending on the actual type the building is related to (specific building class), you may need to implement a new class
	5.	Create xml at path “jsettlers.common\src\main\resources\jsettlers\common\buildings\egyptian\brewery.xml” with the same name you have used for the “EBuildingType” from step 1 (lowercase name)
	6.  Configure the XML as needed, use the "BuildingCreatorApp" for help, gfx building files for images are 13,23,33,43 and gui 14,24,34,44
	6.	For different language support go to “H: jsettlers.graphics\out\production\resources\jsettlers\graphics\localization\” and add the label for the building which is displayed in game

	ROMAN Building TODOS:
	-

	EGYPTIAN Building TODOS:
	- create brewery building (mana)
	- change temple goods mana ressources
	- add Ballistenwerkstatt
	- adjust dx/dy with BuildingCreatorApp (occupier, flags, blocks ... etc)

 	ASIAN Building TODOS:
	- add mana specific buildings
	- change temple goods mana ressources
	- add Ballistenwerkstatt
	- adjust dx/dy with BuildingCreatorApp (occupier, flags, blocks, required ressources ... etc)

 	AMAZON Building TODOS:
	- add mana specific buildings
	- change temple goods mana ressources
	- add Ballistenwerkstatt
	- adjust dx/dy with BuildingCreatorApp (occupier, flags, blocks, required ressources ... etc)
-->

<!ENTITY % imagelinktype "(SETTLER| GUI| LANDSCAPE)">

<!ENTITY % material "(
	NO_MATERIAL|
	AXE|
	BOW|
	BLADE|
	BREAD|
	COAL|
	CROP|
	FISH|
	FISHINGROD|
	FLOUR|
	GOLD|
	GOLDORE|
	HAMMER|
	IRON|
	IRONORE|
	MEAT|
	PICK|
	PIG|
	PLANK|
	SAW|
	SCYTHE|
	SPEAR|
	STONE|
	SWORD|
	TRUNK|
	WATER|
	WINE|
	MEAD|
	GEMS|
	SULFUR|
	RICE|
	KEG|
	LIQUOR|
	GUN_POWDER|
	CANNON_AMMO|
	BALLISTA_AMMO|
	CATAPULT_AMMO|
	WHITE_BREAD|
	BASKET|
	TREE|
	PLANT|
	HONEY|
	EMPTY_BUCKET)
">
<!ENTITY % jobtype "(
	WAIT|
	WALK|
	SHOW|
	HIDE|
	SET_MATERIAL|
	TAKE|
	TAKE_REQUESTED|
	DROP|
	PRE_SEARCH|
	PRE_SEARCH_IN_AREA|
	REQUEST|
	FOLLOW_SEARCHED|
	GO_TO|
	GO_TO_DOCK|
	BUILD_SHIP|
	LOOK_AT|
	PLAY_ACTION1|
	PLAY_ACTION2|
	PLAY_ACTION3|
	EXECUTE|
	AVAILABLE|
	NOT_FULL|
	LOOK_AT_SEARCHED|
	TRY_TAKING_RESOURCE|
	TRY_TAKING_FOOD|
	SMOKE_ON|
	SMOKE_OFF|
	START_WORKING|
	STOP_WORKING|
	REMOTETAKE|
	PIG_PLACE|
	PIG_REMOVE|
	PIG_IS_ADULT|
	PIG_IS_THERE|
	POP_TOOL|
	POP_WEAPON|
	DROP_POPPED|
	GROW_DONKEY|
	CALL_WOUNDED|
	CAN_HEAL|
	HEAL|
	BUILDING_ANIMATION)
">
<!ENTITY % direction "(EAST| SOUTH_EAST| SOUTH_WEST| WEST | NORTH_WEST | NORTH_EAST)">

<!ENTITY % searchtype "(
	FOREIGN_GROUND|
	CUTTABLE_TREE|
	CUTTABLE_STONE|
	PLANTABLE_TREE|
	PLANTABLE_CORN|
	CUTTABLE_CORN|
	PLANTABLE_WINE|
	HARVESTABLE_WINE|
	PLANTABLE_RICE|
	HARVESTABLE_RICE|
	PLANTABLE_HIVE|
	HARVESTABLE_HIVE|
	FISHABLE|
	RIVER|
	ENEMY)
">
<!ENTITY % groundtype "(
	GRASS|
	DRY_GRASS|
	DESERT|
	EARTH|
	MOUNTAIN|
	SNOW|
	WATER|
	SAND|
	FLATTENED|
	RIVER1|
	RIVER2|
	RIVER3|
	RIVER4|
	MOUNTAINBORDER|
	MOUNTAINBORDEROUTER
)">
<!ENTITY % boolean "(true|false)">

<!ELEMENT building (ground+, blocked+, door, constructionStack+, requestStack*, offerStack*, bricklayer+, flag, buildmark*, workcenter?, image*, occupyer*, startjob?, job*) >

<!ATTLIST building
   	worker CDATA #REQUIRED
	workradius CDATA #IMPLIED
	viewdistance CDATA #IMPLIED
	mine (true|false) "false"
>

<!ELEMENT ground EMPTY>
<!ATTLIST ground
	groundtype %groundtype; #REQUIRED
>

<!ELEMENT workcenter EMPTY>
<!ATTLIST workcenter
   dx CDATA #REQUIRED
   dy CDATA #REQUIRED
>

<!ELEMENT blocked EMPTY>
<!ATTLIST blocked
   dx CDATA #REQUIRED
   dy CDATA #REQUIRED
   block (true|false) "true"
>

<!ELEMENT door EMPTY>
<!ATTLIST door
   dx CDATA #REQUIRED
   dy CDATA #REQUIRED
>


<!ELEMENT flag EMPTY>
<!ATTLIST flag
   dx CDATA #REQUIRED
   dy CDATA #REQUIRED
>


<!ELEMENT constructionStack EMPTY>
<!ATTLIST constructionStack
   dx CDATA #REQUIRED
   dy CDATA #REQUIRED
   buildrequired CDATA #REQUIRED
   material %material; #REQUIRED
>

<!ELEMENT requestStack EMPTY>
<!ATTLIST requestStack
   dx CDATA #REQUIRED
   dy CDATA #REQUIRED
   material %material; #REQUIRED
>

<!ELEMENT offerStack EMPTY>
<!ATTLIST offerStack
   dx CDATA #REQUIRED
   dy CDATA #REQUIRED
   material %material; #REQUIRED
>

<!ELEMENT bricklayer EMPTY>
<!ATTLIST bricklayer
   dx CDATA #REQUIRED
   dy CDATA #REQUIRED
   direction %direction; #REQUIRED
>

<!ELEMENT occupyer EMPTY>
<!ATTLIST occupyer
   offsetX CDATA #IMPLIED
   offsetY CDATA #IMPLIED
   type (INFANTRY|BOWMAN) #REQUIRED

   soldierX CDATA #REQUIRED
   soldierY CDATA #REQUIRED
   looksRight (true|false) "true"
>

<!ELEMENT startjob EMPTY>
<!ATTLIST startjob
   name IDREF #REQUIRED
>

<!ELEMENT job EMPTY>
<!ATTLIST job
   name ID #REQUIRED
   type %jobtype; #REQUIRED
   successjob IDREF #REQUIRED
   failjob IDREF #REQUIRED
   dx CDATA #IMPLIED
   dy CDATA #IMPLIED
   time CDATA #IMPLIED
   material %material; #IMPLIED
   direction %direction; #IMPLIED
   search %searchtype; #IMPLIED
   takeMaterialFromMap %boolean; #IMPLIED
   foodOrder CDATA #IMPLIED
>

<!ELEMENT image EMPTY>
<!ATTLIST image
   for (GUI|BUILD|FINAL) #REQUIRED
   name CDATA #IMPLIED
   type %imagelinktype; #IMPLIED
   file CDATA #IMPLIED
   sequence CDATA #IMPLIED
   image CDATA #REQUIRED
>

<!ELEMENT buildmark EMPTY>
<!ATTLIST buildmark
   dx CDATA #REQUIRED
   dy CDATA #REQUIRED
>

=== paulwedeck/settlers-remake/jsettlers.tools/buildings/egyptian/farm.xml
<?xml version="1.1" encoding="UTF-8"?>
<!DOCTYPE building SYSTEM "../building.dtd">
<building worker="FARMER" workradius="6">
	<ground groundtype="GRASS" />
	<ground groundtype="EARTH" />
	<ground groundtype="DESERT" />
	<ground groundtype="DESERTBORDER"/>
	<ground groundtype="DESERTBORDEROUTER"/>
	<ground groundtype="DRY_GRASS"/>
	<ground groundtype="FLATTENED_DESERT"/>
	<ground groundtype="SHARP_FLATTENED_DESERT"/>
	<ground groundtype="FLATTENED" />

	<blocked dx="-3" dy="1" />
	<blocked dx="-3" dy="0" />
	<blocked dx="-4" dy="-3" />
	<blocked dx="-4" dy="-2" />
	<blocked dx="-3" dy="-1" />
	<blocked dx="-3" dy="-2" />
	<blocked dx="-2" dy="-2" />
	<blocked dx="-3" dy="-3" />
	<blocked dx="-4" dy="-4" />
	<blocked dx="-2" dy="-4" />
	<blocked dx="-1" dy="-3" />
	<blocked dx="1" dy="-1" />
	<blocked dx="2" dy="-1" />
	<blocked dx="3" dy="0" />
	<blocked dx="4" dy="1" />
	<blocked dx="2" dy="0" />
	<blocked dx="2" dy="1" />
	<blocked dx="3" dy="3" />
	<blocked dx="2" dy="3" />
	<blocked dx="2" dy="2" />
	<blocked dx="1" dy="0" />
	<blocked dx="1" dy="1" />
	<blocked dx="1" dy="2" />
	<blocked dx="1" dy="3" />
	<blocked dx="1" dy="4" />
	<blocked dx="0" dy="-2" />
	<blocked dx="0" dy="-1" />
	<blocked dx="0" dy="0" />
	<blocked dx="0" dy="1" />
	<blocked dx="0" dy="2" />
	<blocked dx="0" dy="3" />
	<blocked dx="-1" dy="-2" />
	<blocked dx="-1" dy="-1" />
	<blocked dx="-1" dy="0" />
	<blocked dx="-1" dy="1" />
	<blocked dx="-1" dy="2" />
	<blocked dx="-2" dy="-1" />
	<blocked dx="-2" dy="0" />
	<blocked dx="-2" dy="1" />
	<blocked dx="-2" dy="2" />
	<blocked dx="-2" dy="-3" />
	<blocked dx="-3" dy="-4" />
	<blocked dx="-4" dy="-5" />
	<blocked dx="-3" dy="-5" />
	<blocked dx="1" dy="6" />
	<blocked dx="0" dy="5" />
	<blocked dx="1" dy="5" />
	<blocked dx="0" dy="4" />
	<blocked dx="-4" dy="-1" />
	<blocked dx="-5" dy="-2" />
	<blocked dx="-4" dy="-7" />
	<blocked dx="-5" dy="-7" />
	<blocked dx="-6" dy="-6" />
	<blocked dx="-6" dy="-5" />
	<blocked dx="-6" dy="-4" />
	<blocked dx="-6" dy="-7" />
	<blocked dx="-3" dy="-7" />
	<blocked dx="-2" dy="-7" />
	<blocked dx="-1" dy="-5" />
	<blocked dx="-2" dy="-6" />
	<blocked dx="-2" dy="-5" />
	<blocked dx="-1" dy="-4" />
	<blocked dx="1" dy="-2" />
	<blocked dx="1" dy="-3" />
	<blocked dx="-4" dy="-6" />
	<blocked dx="-3" dy="-6" />
	<blocked dx="-5" dy="-6" />
	<blocked dx="-5" dy="-5" />
	<blocked dx="-5" dy="-4" />
	<blocked dx="-5" dy="-3" />
	<blocked dx="-1" dy="-6" />
	<blocked dx="0" dy="-5" />
	<blocked dx="1" dy="-4" />
	<blocked dx="2" dy="-2" />
	<blocked dx="3" dy="-1" />
	<blocked dx="2" dy="-3" />
	<blocked dx="-1" dy="3" />
	<blocked dx="0" dy="-3" />
	<blocked dx="0" dy="-4" />
	<blocked dx="-3" dy="2" />
	<blocked dx="-2" dy="3" />
	<blocked dx="-1" dy="4" />
	<blocked dx="-4" dy="0" />
	<blocked dx="3" dy="1" />
	<blocked dx="4" dy="4" />
	<blocked dx="4" dy="2" />
	<blocked dx="3" dy="2" />

	<blocked dx="-3" dy="3" block="false" />
	<blocked dx="-2" dy="4" block="false" />
	<blocked dx="-1" dy="5" block="false" />
	<blocked dx="0" dy="6" block="false" />
	<blocked dx="2" dy="5" block="false" />
	<blocked dx="2" dy="4" block="false" />
	<blocked dx="3" dy="5" block="false" />
	<blocked dx="5" dy="0" block="false" />
	<blocked dx="4" dy="-1" block="false" />
	<blocked dx="3" dy="-2" block="false" />
	<blocked dx="-5" dy="-1" block="false" />
	<blocked dx="3" dy="4" block="false" />
	<blocked dx="4" dy="0" block="false" />
	<blocked dx="5" dy="2" block="false" />
	<blocked dx="5" dy="1" block="false" />
	<blocked dx="5" dy="4" block="false" />
	<blocked dx="4" dy="5" block="false" />
	<blocked dx="2" dy="6" block="false" />
	<blocked dx="2" dy="7" block="false" />
	<blocked dx="1" dy="7" block="false" />
	<blocked dx="-6" dy="-3" block="false" />
	<blocked dx="-7" dy="-5" block="false" />
	<blocked dx="-7" dy="-6" block="false" />
	<blocked dx="-7" dy="-7" block="false" />
	<blocked dx="-7" dy="-8" block="false" />
	<blocked dx="-6" dy="-8" block="false" />
	<blocked dx="-5" dy="-8" block="false" />
	<blocked dx="-4" dy="-8" block="false" />
	<blocked dx="-3" dy="-8" block="false" />
	<blocked dx="-2" dy="-8" block="false" />
	<blocked dx="-1" dy="-7" block="false" />
	<blocked dx="0" dy="-6" block="false" />
	<blocked dx="5" dy="5" block="false" />
	<blocked dx="5" dy="6" block="false" />
	<blocked dx="4" dy="6" block="false" />
	<blocked dx="3" dy="6" block="false" />
	<blocked dx="2" dy="8" block="false" />
	<blocked dx="1" dy="-5" block="false" />
	<blocked dx="2" dy="-4" block="false" />
	<blocked dx="-4" dy="1" block="false" />
	<blocked dx="4" dy="3" block="false" />
	<blocked dx="5" dy="3" block="false" />
	<blocked dx="6" dy="4" block="false" />
	<blocked dx="6" dy="5" block="false" />
	<blocked dx="-6" dy="-2" block="false" />
	<blocked dx="-7" dy="-4" block="false" />
	<blocked dx="-5" dy="0" block="false" />
	<blocked dx="-4" dy="2" block="false" />
	<blocked dx="3" dy="-3" block="false" />

	<door dx="4" dy="3" />

	<constructionStack dx="6" dy="5" material="PLANK" buildrequired="3" />
	<constructionStack dx="4" dy="6" material="STONE" buildrequired="8" />
	<constructionStack dx="5" dy="6" material="STONE" buildrequired="1" />
	<offerStack dx="6" dy="4" material="CROP" />

	<bricklayer dx="5" dy="3" direction="NORTH_WEST" />
	<bricklayer dx="2" dy="5" direction="NORTH_WEST" />
	<bricklayer dx="4" dy="5" direction="NORTH_WEST" />
	<bricklayer dx="-2" dy="4" direction="NORTH_EAST" />
	<bricklayer dx="-3" dy="3" direction="NORTH_EAST" />
	<bricklayer dx="-1" dy="5" direction="NORTH_EAST" />

	<flag dx="0" dy="-3" />

	<buildmark dx="4" dy="1" />
	<buildmark dx="4" dy="3" />
	<buildmark dx="1" dy="5" />
	<buildmark dx="-6" dy="-4" />
	<buildmark dx="-4" dy="-7" />
	<buildmark dx="-2" dy="-7" />

	<workcenter dx="2" dy="10"/>

	<image file="24" for="GUI" type="GUI" sequence="69" image="0"/>
	<image file="23" type="SETTLER" for="FINAL" image="0" sequence="17"/>
	<image file="23" type="SETTLER" for="BUILD" image="1" sequence="17"/>

 </building>

=== paulwedeck/settlers-remake/jsettlers.tools/buildings/asian/pig_farm.xml
<?xml version="1.1" encoding="UTF-8"?>
<!DOCTYPE building SYSTEM "../building.dtd">
<building worker="PIG_FARMER" workradius="0">
	<ground groundtype="GRASS" />
	<ground groundtype="EARTH" />
	<ground groundtype="FLATTENED" />

	<blocked dx="2" dy="4" />
	<blocked dx="5" dy="3" />
	<blocked dx="4" dy="4" />
	<blocked dx="5" dy="2" />
	<blocked dx="4" dy="3" />
	<blocked dx="4" dy="2" />
	<blocked dx="4" dy="1" />
	<blocked dx="4" dy="0" />
	<blocked dx="3" dy="-1" />
	<blocked dx="2" dy="-2" />
	<blocked dx="1" dy="-2" />
	<blocked dx="1" dy="-3" />
	<blocked dx="1" dy="-1" />
	<blocked dx="1" dy="0" />
	<blocked dx="0" dy="0" />
	<blocked dx="0" dy="-1" />
	<blocked dx="0" dy="-2" />
	<blocked dx="0" dy="-3" />
	<blocked dx="-1" dy="-4" />
	<blocked dx="-2" dy="-5" />
	<blocked dx="-2" dy="-4" />
	<blocked dx="-2" dy="-3" />
	<blocked dx="-2" dy="-2" />
	<blocked dx="-3" dy="-3" />
	<blocked dx="-3" dy="-4" />
	<blocked dx="-3" dy="-2" />
	<blocked dx="-3" dy="-1" />
	<blocked dx="-3" dy="0" />
	<blocked dx="-2" dy="-1" />
	<blocked dx="-2" dy="0" />
	<blocked dx="-1" dy="-3" />
	<blocked dx="-1" dy="-2" />
	<blocked dx="-1" dy="-1" />
	<blocked dx="-1" dy="0" />
	<blocked dx="0" dy="-4" />
	<blocked dx="-1" dy="1" />
	<blocked dx="-1" dy="2" />
	<blocked dx="2" dy="-1" />
	<blocked dx="3" dy="0" />
	<blocked dx="3" dy="4" />
	<blocked dx="-3" dy="-5" />
	<blocked dx="2" dy="3" />
	<blocked dx="3" dy="3" />
	<blocked dx="5" dy="4" />
	<blocked dx="6" dy="1" />
	<blocked dx="5" dy="1" />
	<blocked dx="5" dy="0" />
	<blocked dx="4" dy="-1" />
	<blocked dx="-4" dy="0" />
	<blocked dx="-4" dy="-4" />
	<blocked dx="-4" dy="-3" />
	<blocked dx="-4" dy="-2" />
	<blocked dx="-4" dy="-1" />
	<blocked dx="-4" dy="-5" />
	<blocked dx="-2" dy="1" />
	<blocked dx="-1" dy="3" />
	<blocked dx="6" dy="2" />

	<blocked dx="5" dy="5" block="false" />
	<blocked dx="6" dy="5" block="false" />
	<blocked dx="6" dy="4" block="false" />
	<blocked dx="6" dy="3" block="false" />
	<blocked dx="7" dy="2" block="false" />
	<blocked dx="3" dy="-2" block="false" />
	<blocked dx="2" dy="-3" block="false" />
	<blocked dx="1" dy="-4" block="false" />
	<blocked dx="0" dy="-5" block="false" />
	<blocked dx="-1" dy="-5" block="false" />
	<blocked dx="-2" dy="-6" block="false" />
	<blocked dx="-3" dy="-6" block="false" />
	<blocked dx="-4" dy="1" block="false" />
	<blocked dx="-3" dy="2" block="false" />
	<blocked dx="-1" dy="4" block="false" />
	<blocked dx="-2" dy="2" block="false" />
	<blocked dx="-2" dy="3" block="false" />
	<blocked dx="0" dy="4" block="false" />
	<blocked dx="1" dy="5" block="false" />
	<blocked dx="1" dy="4" block="false" />
	<blocked dx="1" dy="3" block="false" />
	<blocked dx="1" dy="2" block="false" />
	<blocked dx="1" dy="1" block="false" />
	<blocked dx="2" dy="1" block="false" />
	<blocked dx="3" dy="2" block="false" />
	<blocked dx="3" dy="1" block="false" />
	<blocked dx="2" dy="0" block="false" />
	<blocked dx="2" dy="2" block="false" />
	<blocked dx="-4" dy="-6" block="false" />
	<blocked dx="0" dy="1" block="false" />
	<blocked dx="5" dy="-1" block="false" />
	<blocked dx="4" dy="-2" block="false" />
	<blocked dx="3" dy="-3" block="false" />
	<blocked dx="2" dy="5" block="false" />
	<blocked dx="3" dy="5" block="false" />
	<blocked dx="4" dy="5" block="false" />
	<blocked dx="0" dy="5" block="false" />
	<blocked dx="6" dy="0" block="false" />
	<blocked dx="7" dy="1" block="false" />
	<blocked dx="7" dy="3" block="false" />
	<blocked dx="-5" dy="0" block="false" />
	<blocked dx="-5" dy="-2" block="false" />
	<blocked dx="-5" dy="-1" block="false" />
	<blocked dx="-5" dy="-3" block="false" />
	<blocked dx="-5" dy="-4" block="false" />
	<blocked dx="-5" dy="-5" block="false" />
	<blocked dx="-5" dy="-6" block="false" />
	<blocked dx="0" dy="3" block="false" />
	<blocked dx="0" dy="2" block="false" />
	<blocked dx="-3" dy="1" block="false" />

	<door dx="0" dy="1" />

	<constructionStack dx="1" dy="5" material="PLANK" buildrequired="8" />
	<constructionStack dx="3" dy="5" material="STONE" buildrequired="3" />
	<requestStack dx="5" dy="5" material="WATER" />
	<requestStack dx="6" dy="4" material="CROP" />
	<offerStack dx="2" dy="5" material="PIG" />

	<bricklayer dx="-3" dy="2" direction="NORTH_EAST" />
	<bricklayer dx="-2" dy="3" direction="NORTH_EAST" />
	<bricklayer dx="6" dy="4" direction="NORTH_WEST" />
	<bricklayer dx="7" dy="3" direction="NORTH_WEST" />

	<flag dx="-2" dy="-3" />

	<buildmark dx="4" dy="5" />
	<buildmark dx="-4" dy="0" />
	<buildmark dx="-4" dy="-5" />
	<buildmark dx="0" dy="-5" />
	<buildmark dx="6" dy="1" />



	<pigFeedPosition dx="2" dy="1"/>

	<animalPosition dx="2" dy="0"/>
	<animalPosition dx="2" dy="2"/>
	<animalPosition dx="3" dy="1"/>
	<animalPosition dx="3" dy="2"/>

	<image file="34" type="GUI" for="GUI" image="0" sequence="69" />
	<image file="33" type="SETTLER" for="FINAL" image="0" sequence="18" />
	<image file="33" type="SETTLER" for="BUILD" image="1" sequence="18" />

</building>

=== paulwedeck/settlers-remake/jsettlers.tools/buildings/roman/lumberjack.xml
<?xml version="1.1" encoding="UTF-8"?><!DOCTYPE building SYSTEM "../building.dtd">

<building worker="LUMBERJACK" workradius="30">
	<ground groundtype="GRASS"/>
	<ground groundtype="EARTH"/>
	<ground groundtype="FLATTENED"/>

	<blocked dx="-3" dy="2"/>
	<blocked dx="-2" dy="2"/>
	<blocked dx="-3" dy="1"/>
	<blocked dx="-3" dy="-1"/>
	<blocked dx="-3" dy="-2"/>
	<blocked dx="-3" dy="-3"/>
	<blocked dx="-2" dy="-3"/>
	<blocked dx="-1" dy="-2"/>
	<blocked dx="0" dy="-1"/>
	<blocked dx="1" dy="0"/>
	<blocked dx="-1" dy="-3"/>
	<blocked dx="0" dy="-2"/>
	<blocked dx="1" dy="-1"/>
	<blocked dx="3" dy="1"/>
	<blocked dx="3" dy="2"/>
	<blocked dx="2" dy="1"/>
	<blocked dx="-2" dy="-1"/>
	<blocked dx="-2" dy="-2"/>
	<blocked dx="-1" dy="-1"/>
	<blocked dx="0" dy="0"/>
	<blocked dx="1" dy="1"/>
	<blocked dx="2" dy="2"/>
	<blocked dx="3" dy="3"/>
	<blocked dx="2" dy="3"/>
	<blocked dx="1" dy="2"/>
	<blocked dx="0" dy="1"/>
	<blocked dx="-1" dy="0"/>
	<blocked dx="-2" dy="0"/>
	<blocked dx="0" dy="2"/>
	<blocked dx="1" dy="3"/>
	<blocked dx="2" dy="0"/>
	<blocked dx="-3" dy="0"/>
	<blocked dx="-2" dy="1"/>
	<blocked block="false" dx="-4" dy="2"/>
	<blocked block="false" dx="-3" dy="3"/>
	<blocked block="false" dx="-2" dy="3"/>
	<blocked block="false" dx="-1" dy="3"/>
	<blocked block="false" dx="-1" dy="2"/>
	<blocked block="false" dx="-1" dy="1"/>
	<blocked block="false" dx="0" dy="3"/>
	<blocked block="false" dx="1" dy="5"/>
	<blocked block="false" dx="1" dy="4"/>
	<blocked block="false" dx="2" dy="5"/>
	<blocked block="false" dx="3" dy="5"/>
	<blocked block="false" dx="2" dy="4"/>
	<blocked block="false" dx="3" dy="4"/>
	<blocked block="false" dx="4" dy="4"/>
	<blocked block="false" dx="4" dy="3"/>
	<blocked block="false" dx="4" dy="2"/>
	<blocked block="false" dx="4" dy="1"/>
	<blocked block="false" dx="3" dy="0"/>
	<blocked block="false" dx="2" dy="-1"/>
	<blocked block="false" dx="1" dy="-2"/>
	<blocked block="false" dx="0" dy="-3"/>
	<blocked block="false" dx="-1" dy="-4"/>
	<blocked block="false" dx="-2" dy="-4"/>
	<blocked block="false" dx="-3" dy="-4"/>
	<blocked block="false" dx="-4" dy="-4"/>
	<blocked block="false" dx="-4" dy="-3"/>
	<blocked block="false" dx="-4" dy="-2"/>
	<blocked block="false" dx="0" dy="4"/>
	<blocked block="false" dx="-4" dy="-1"/>
	<blocked block="false" dx="-4" dy="0"/>
	<blocked block="false" dx="-4" dy="1"/>

	<door dx="-1" dy="1"/>
	<constructionStack buildrequired="2" dx="0" dy="4" material="STONE"/>
	<constructionStack buildrequired="2" dx="3" dy="5" material="PLANK"/>
	<offerStack dx="0" dy="3" material="TRUNK"/>

	<bricklayer direction="NORTH_EAST" dx="-1" dy="2"/>
	<bricklayer direction="NORTH_EAST" dx="0" dy="3"/>
	<bricklayer direction="NORTH_WEST" dx="4" dy="3"/>
	<bricklayer direction="NORTH_WEST" dx="3" dy="4"/>

	<flag dx="-3" dy="-3"/>

	<buildmark dx="-3" dy="-1"/>
	<buildmark dx="1" dy="3"/>
	<buildmark dx="3" dy="3"/>
	<buildmark dx="3" dy="1"/>
	<buildmark dx="-1" dy="-3"/>
	<buildmark dx="-3" dy="1"/>

	<image file="14" for="GUI" image="0" sequence="0" type="GUI"/>
	<image file="13" for="FINAL" image="0" sequence="0" type="SETTLER"/>
	<image file="13" for="BUILD" image="1" sequence="0" type="SETTLER"/>

</building>

=== paulwedeck/settlers-remake/jsettlers.tools/buildings/amazon/sawmill.xml
<?xml version="1.1" encoding="UTF-8"?>
<!DOCTYPE building SYSTEM "../building.dtd">
<building worker="SAWMILLER">
	<ground groundtype="GRASS"/>
	<ground groundtype="EARTH"/>
	<ground groundtype="FLATTENED"/>

	<blocked dx="4" dy="4" />
	<blocked dx="4" dy="1" />
	<blocked dx="3" dy="1" />
	<blocked dx="2" dy="0" />
	<blocked dx="1" dy="0" />
	<blocked dx="1" dy="-1" />
	<blocked dx="-1" dy="-2" />
	<blocked dx="3" dy="0" />
	<blocked dx="0" dy="-2" />
	<blocked dx="0" dy="-1" />
	<blocked dx="2" dy="1" />
	<blocked dx="3" dy="2" />
	<blocked dx="3" dy="3" />
	<blocked dx="3" dy="4" />
	<blocked dx="1" dy="3" />
	<blocked dx="0" dy="2" />
	<blocked dx="0" dy="3" />
	<blocked dx="2" dy="3" />
	<blocked dx="2" dy="2" />
	<blocked dx="1" dy="1" />
	<blocked dx="1" dy="2" />
	<blocked dx="0" dy="0" />
	<blocked dx="0" dy="1" />
	<blocked dx="-1" dy="-1" />
	<blocked dx="-1" dy="0" />
	<blocked dx="-1" dy="1" />
	<blocked dx="-1" dy="2" />
	<blocked dx="-2" dy="1" />
	<blocked dx="-2" dy="0" />
	<blocked dx="-2" dy="-1" />
	<blocked dx="-2" dy="-2" />
	<blocked dx="2" dy="-1" />
	<blocked dx="1" dy="-2" />
	<blocked dx="-3" dy="-1" />
	<blocked dx="-3" dy="-2" />
	<blocked dx="-3" dy="0" />
	<blocked dx="4" dy="2" />
	<blocked dx="1" dy="4" />
	<blocked dx="2" dy="4" />

	<blocked dx="5" dy="4" block="false" />
	<blocked dx="5" dy="5" block="false" />
	<blocked dx="4" dy="5" block="false" />
	<blocked dx="2" dy="5" block="false" />
	<blocked dx="1" dy="5" block="false" />
	<blocked dx="0" dy="4" block="false" />
	<blocked dx="-1" dy="3" block="false" />
	<blocked dx="-2" dy="2" block="false" />
	<blocked dx="-3" dy="1" block="false" />
	<blocked dx="-3" dy="-3" block="false" />
	<blocked dx="0" dy="-3" block="false" />
	<blocked dx="1" dy="-3" block="false" />
	<blocked dx="2" dy="-2" block="false" />
	<blocked dx="3" dy="-1" block="false" />
	<blocked dx="4" dy="0" block="false" />
	<blocked dx="5" dy="1" block="false" />
	<blocked dx="5" dy="2" block="false" />
	<blocked dx="3" dy="5" block="false" />
	<blocked dx="5" dy="3" block="false" />
	<blocked dx="-2" dy="-3" block="false" />
	<blocked dx="-1" dy="-3" block="false" />
	<blocked dx="-4" dy="-3" block="false" />
	<blocked dx="-4" dy="-2" block="false" />
	<blocked dx="-4" dy="-1" block="false" />
	<blocked dx="-4" dy="0" block="false" />
	<blocked dx="4" dy="3" block="false" />
	<blocked dx="2" dy="6" block="false" />
	<blocked dx="3" dy="6" block="false" />

	<door dx="4" dy="3" />

	<constructionStack dx="2" dy="6" material="PLANK" buildrequired="4" />
	<constructionStack dx="0" dy="4" material="STONE" buildrequired="3" />
	<requestStack dx="-2" dy="2" material="TRUNK" />
	<offerStack dx="5" dy="5" material="PLANK" />

	<bricklayer dx="-1" dy="3" direction="NORTH_EAST" />
	<bricklayer dx="0" dy="4" direction="NORTH_EAST" />
	<bricklayer dx="-2" dy="2" direction="NORTH_EAST" />
	<bricklayer dx="5" dy="3" direction="NORTH_WEST" />

	<flag dx="1" dy="-2" />

	<buildmark dx="1" dy="4" />
	<buildmark dx="4" dy="2" />
	<buildmark dx="-2" dy="1" />
	<buildmark dx="-3" dy="-2" />
	<buildmark dx="0" dy="-2" />

	<sawmillerWorkPosition dx="3" dy="5" direction="NORTH_WEST"/>

	<image file="44" type="GUI" for="GUI" image="0" sequence="6" />
    <image file="43" type="SETTLER" for="FINAL" image="0" sequence="6"/>
    <image file="43" type="SETTLER" for="BUILD" image="1" sequence="6"/>
</building>

=== paulwedeck/settlers-remake/jsettlers.tools/buildings/egyptian/barrack.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE building SYSTEM "../building.dtd" >
<building worker="" workradius="6">
	<ground groundtype="GRASS" />
	<ground groundtype="EARTH" />
	<ground groundtype="DESERT" />
	<ground groundtype="DESERTBORDER"/>
	<ground groundtype="DESERTBORDEROUTER"/>
	<ground groundtype="DRY_GRASS"/>
	<ground groundtype="FLATTENED_DESERT"/>
	<ground groundtype="SHARP_FLATTENED_DESERT"/>
	<ground groundtype="FLATTENED" />

	<blocked dx="0" dy="0" />
	<blocked dx="1" dy="1" />
	<blocked dx="1" dy="2" />
	<blocked dx="0" dy="1" />
	<blocked dx="-1" dy="0" />
	<blocked dx="-2" dy="-1" />
	<blocked dx="-2" dy="-2" />
	<blocked dx="-1" dy="-2" />
	<blocked dx="-1" dy="-3" />
	<blocked dx="0" dy="-3" />
	<blocked dx="1" dy="-3" />
	<blocked dx="2" dy="-2" />
	<blocked dx="3" dy="-1" />
	<blocked dx="4" dy="2" />
	<blocked dx="4" dy="1" />
	<blocked dx="-1" dy="-1" />
	<blocked dx="0" dy="-1" />
	<blocked dx="0" dy="-2" />
	<blocked dx="1" dy="-2" />
	<blocked dx="1" dy="-1" />
	<blocked dx="1" dy="0" />
	<blocked dx="2" dy="-1" />
	<blocked dx="2" dy="0" />
	<blocked dx="-2" dy="-3" />
	<blocked dx="0" dy="-4" />
	<blocked dx="-1" dy="-4" />
	<blocked dx="-2" dy="-4" />
	<blocked dx="-2" dy="-5" />
	<blocked dx="-1" dy="-5" />
	<blocked dx="3" dy="1" />
	<blocked dx="-3" dy="0" />
	<blocked dx="-2" dy="1" />
	<blocked dx="-2" dy="0" />
	<blocked dx="-1" dy="1" />
	<blocked dx="3" dy="3" />
	<blocked dx="3" dy="2" />
	<blocked dx="4" dy="0" />
	<blocked dx="2" dy="1" />
	<blocked dx="-3" dy="-3" />
	<blocked dx="-3" dy="-2" />
	<blocked dx="-3" dy="-1" />
	<blocked dx="-3" dy="-4" />
	<blocked dx="-3" dy="-5" />
	<blocked dx="-4" dy="-3" />
	<blocked dx="-4" dy="-4" />
	<blocked dx="-4" dy="-5" />
	<blocked dx="-4" dy="-1" />
	<blocked dx="3" dy="0" />
	<blocked dx="3" dy="-2" />
	<blocked dx="-4" dy="-2" />
	<blocked dx="2" dy="2" />

	<blocked dx="2" dy="3" block="false" />
	<blocked dx="1" dy="3" block="false" />
	<blocked dx="-1" dy="2" block="false" />
	<blocked dx="0" dy="2" block="false" />
	<blocked dx="1" dy="-4" block="false" />
	<blocked dx="5" dy="2" block="false" />
	<blocked dx="5" dy="3" block="false" />
	<blocked dx="4" dy="3" block="false" />
	<blocked dx="-2" dy="-6" block="false" />
	<blocked dx="-1" dy="-6" block="false" />
	<blocked dx="-3" dy="-6" block="false" />
	<blocked dx="0" dy="-5" block="false" />
	<blocked dx="-3" dy="1" block="false" />
	<blocked dx="-2" dy="2" block="false" />
	<blocked dx="3" dy="4" block="false" />
	<blocked dx="4" dy="4" block="false" />
	<blocked dx="5" dy="4" block="false" />
	<blocked dx="5" dy="0" block="false" />
	<blocked dx="5" dy="1" block="false" />
	<blocked dx="-4" dy="-6" block="false" />
	<blocked dx="-5" dy="-2" block="false" />
	<blocked dx="-5" dy="-6" block="false" />
	<blocked dx="-5" dy="-5" block="false" />
	<blocked dx="-5" dy="-4" block="false" />
	<blocked dx="-5" dy="-3" block="false" />
	<blocked dx="-5" dy="-1" block="false" />
	<blocked dx="-4" dy="0" block="false" />
	<blocked dx="2" dy="-3" block="false" />
	<blocked dx="2" dy="-4" block="false" />
	<blocked dx="3" dy="-3" block="false" />
	<blocked dx="4" dy="-2" block="false" />
	<blocked dx="4" dy="-1" block="false" />

	<door dx="-3" dy="1" />

	<constructionStack dx="3" dy="4" material="PLANK" buildrequired="3" />
	<constructionStack dx="1" dy="3" material="STONE" buildrequired="6" />
	<requestStack dx="1" dy="3" material="SPEAR" />
	<requestStack dx="0" dy="2" material="SWORD" />
	<requestStack dx="2" dy="3" material="BOW" />

	<bricklayer dx="0" dy="2" direction="NORTH_EAST" />
	<bricklayer dx="5" dy="3" direction="NORTH_WEST" />
	<bricklayer dx="-3" dy="1" direction="NORTH_EAST" />
	<bricklayer dx="5" dy="2" direction="NORTH_EAST" />

	<flag dx="-5" dy="-3" />

	<buildmark dx="-2" dy="-1" />
	<buildmark dx="0" dy="1" />
	<buildmark dx="2" dy="-2" />
	<buildmark dx="-1" dy="-5" />
	<buildmark dx="5" dy="0" />
	<buildmark dx="-4" dy="0" />
	<buildmark dx="-1" dy="1" />
	<buildmark dx="-4" dy="-5" />
	<buildmark dx="-1" dy="-4" />
	<buildmark dx="3" dy="-2" />
	<buildmark dx="3" dy="3" />


	<workcenter dx="-1" dy="3"/>

	<image file="24" type="GUI" for="GUI" image="0" sequence="57"/>
	<image file="23" type="SETTLER" for="FINAL" image="0" sequence="33"/>
	<image file="23" type="SETTLER" for="BUILD" image="1" sequence="33"/>

</building>
